version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.13

jobs:
  test: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.thebaltimorebanner.com

workflows:
  test:
    jobs:
      - test